<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PharmacyStock.Entities\PharmacyStock.Entities.csproj" />
    <ProjectReference Include="..\PharmacyStock.DataAccess\PharmacyStock.DataAccess.csproj" />
    <ProjectReference Include="..\PharmacyStock.DTO\PharmacyStock.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
